development:
  host: localhost
  port: 27017 #<%= ENV['MONGOID_PORT'] %>
  database: lojinha

test:
  host: localhost
  port: 27017 #<%= ENV['MONGOID_PORT'] %>
  database: lojinha #<%= ENV['MONGOID_DATABASE'] %>

# set these environment variables on your prod server
production:
  host: <%= ENV['MONGOID_HOST'] %>
  port: <%= ENV['MONGOID_PORT'] %>
  username: <%= ENV['MONGOID_USERNAME'] %>
  password: <%= ENV['MONGOID_PASSWORD'] %>
  database: <%= ENV['MONGOID_DATABASE'] %> 

